"""add linked accounts (oauth connections)

Revision ID: 8da3e22e5f65
Revises: 4739fb0d1292
Create Date: 2026-06-20 16:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da3e22e5f65'
down_revision: Union[str, None] = '4739fb0d1292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=190), nullable=False),
    sa.Column('external_handle', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('instance_url', sa.String(length=300), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'external_id', name='uq_linked_user_provider_extid')
    )
    with op.batch_alter_table('linked_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linked_accounts_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_linked_accounts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linked_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linked_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_linked_accounts_provider'))

    op.drop_table('linked_accounts')
    # ### end Alembic commands ###
