"""initial schema

Revision ID: 82bf36cfd7f0
Revises: 
Create Date: 2026-06-18 18:51:23.170562

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bf36cfd7f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('access_token', sa.String(length=2000), nullable=True),
    sa.Column('refresh_token', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('connectors_used', sa.String(length=200), nullable=True),
    sa.Column('mentions_found', sa.Integer(), nullable=False),
    sa.Column('new_mentions', sa.Integer(), nullable=False),
    sa.Column('score_before', sa.Float(), nullable=True),
    sa.Column('score_after', sa.Float(), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_user_id'), ['user_id'], unique=False)

    op.create_table('verification_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_verification_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('mentions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentions_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentions_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentions_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentions_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mention_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_mention_id'), ['mention_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mention_id', sa.String(length=36), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.String(length=20), nullable=False),
    sa.Column('context', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('analyzer', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_mention_id'), ['mention_id'], unique=True)

    op.create_table('cleanup_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mention_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('automated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleanup_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cleanup_actions_mention_id'), ['mention_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cleanup_actions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleanup_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleanup_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_cleanup_actions_mention_id'))

    op.drop_table('cleanup_actions')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_mention_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_mention_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentions_user_id'))
        batch_op.drop_index(batch_op.f('ix_mentions_status'))
        batch_op.drop_index(batch_op.f('ix_mentions_source'))
        batch_op.drop_index(batch_op.f('ix_mentions_scan_id'))
        batch_op.drop_index(batch_op.f('ix_mentions_external_id'))

    op.drop_table('mentions')
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_verification_tokens_token'))

    op.drop_table('verification_tokens')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_user_id'))

    op.drop_table('scans')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
